name: Release Create Onchain Agent to NPM

on:
  workflow_dispatch:

jobs:
  deploy-npm-create-onchain-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: ./typescript
      - name: Install, build and publish create-onchain-agent
        working-directory: ./typescript/create-onchain-agent
        run: |
          npm ci
          npm run build
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
